### PR TITLE
Profile Server Side (and some Overview page additions)

### PR DESCRIPTION
**Pull request by SamCrowe**
Profile Page: The profile page is now correctly laid out. Content boxes are split up appropriately, (before the two content boxes on the right were just one content box, causing scrolling issues.). The main content box on the right consists of a scrollbar that only appears when necessary, it is a custom scrollbar which matches the colour scheme of the web application.

Users can hover over their profile image and a "plus" icon appears, notifying the user that they can upload a new image by directly clicking onto it. Error handling is added to the uploading of pictures, meaning that if a file is too large or the wrong file type then an error message will be displayed under the profile image when it has redirected to the page.

Users can enrol and un-enrol modules on this page, if the user is a student they are allowed 5 modules, and if the user is a lecturer then they are only allowed to be enrolled onto one module. A user is not able to enrol on more modules than they are allowed. When a user un-enrols from a subject, if they have taken a quiz on that subject, that data will be removed from the database.

Removed the limit from the displaying of forum posts and threads in the content box. Before there was no plan to make the content boxes scrollable, but with the addition of the scroll bar the limit of the posts being displayed has been removed. When a post it clicked on, it redirects the user to that exact post.

Changed the 'tick' for confirming the upload of an image to a button with the text 'Confirm Upload'

Multiple bugs have been fixed, such as data not fully filling the content box, and other issues such as the sidebar drop down menu bug.

Overview page: Various javascript and php files have been added to extract data from the database and display it in a graph, at the moment the correct data is not being pulled out to the graph.

### CODE REVIEW

**Comment by James-Prescott** [comment]
- [ ] Change anything that references classes as ‘Modules’ to ‘Subjects’ as it actually displays subjects when clicked, not modules.
- [ ] Add the topic name to each item the ‘posts’ list so the user can distinguish which thread was replied to.
- [ ] When hovering over one of the 3 tab boxes, the border-bottom colour doesn’t change to the hovered colour. Add a rule on hover that also sets the border-bottom colour to the on hover background colour so you can’t see a visible difference.
- [ ] Change ‘posts’ to ‘replies’ as it could be confusing for the user to tell the difference between ‘questions’ and ‘posts’.
- [ ] Instead of redirecting lecturers to the quiz when clicking on a subject/class, redirect them to dashboard.php (which will show their subject automatically).
- [ ] Add an inherited css rule to fix the rollover effect on the profile image by nesting the <I> element  (the ‘+’ icon) inside the  tag, then setting a css rule to keep the rollover effect when the <I> element is rolled over.
- [ ] Add mailto: onclick to email addresses so users can send emails directly to a lecturer from the app.
- [ ] Add cursor: pointer hover to email address or make it into a link so it looks like you can click on it.
- [ ] Change font of email address so it matches the font style of the rest of the site.
- [ ] Change ‘edit module’ text to a link/button (something that looks clickable).

**Comment by James-Prescott** [comment]
Is this list up to date Sam? Is it ready to merge yet?

**Comment by SamCrowe** [comment]
Completed the checklist, this is now ready to be merged.

**Comment by James-Prescott** [comment]
Awesome. Looks good to me. Merged!

**Pull request merged**
